name: Trojan-Go Plugin Release Build
on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Release (y/n)'
        required: false
      tag:
        description: 'Release Tag'
        required: false
jobs:
  native:
    name: Native Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version: 1.17.13
      - name: Trojan-Go Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            plugin/trojan-go/src/main/jniLibs
          key: ${{ hashFiles('.github/workflows/*', 'bin/lib/trojan-go/*') }}
      - name: Native Build
        run: |
          export ANDROID_NDK_HOME=${ANDROID_NDK_LATEST_HOME}
          ./run plugin trojan_go
  build:
    name: Gradle Build
    runs-on: ubuntu-latest
    needs:
      - native
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Trojan-Go Cache
        uses: actions/cache@v4
        with:
          path: |
            plugin/trojan-go/src/main/jniLibs
          key: ${{ hashFiles('.github/workflows/*', 'bin/lib/trojan-go/*') }}
      - name: Release Build
        env:
          SKIP_BUILD: on
          BUILD_PLUGIN: trojan-go
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          export LOCAL_PROPERTIES="${{ secrets.LOCAL_PROPERTIES }}"
          ./run init action library
          ./gradlew :plugin:trojan-go:assembleOssRelease
          APK=$(find plugin/trojan-go/build/outputs/apk -name '*arm64-v8a*.apk')
          APK=$(dirname "$APK")
          echo "APK=$APK" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v4
        with:
          name: APKs
          path: ${{ env.APK }}
  publish:
    name: Publish Release
    if: github.event.inputs.publish == 'y' && github.event.inputs.tag != ''
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Donwload Artifacts
        uses: actions/download-artifact@v4
        with:
          name: APKs
          path: artifacts
      - name: Release
        run: |
          wget -O ghr.tar.gz https://github.com/tcnksm/ghr/releases/download/v0.16.2/ghr_v0.16.2_linux_amd64.tar.gz
          tar -xvf ghr.tar.gz
          mv ghr*linux_amd64/ghr .
          mkdir apks
          find artifacts -name "*.apk" -exec cp {} apks \;
          ./ghr -replace -prerelease -t "${{ github.token }}" -n "${{ github.event.inputs.tag }}" "${{ github.event.inputs.tag }}" apks
